name: polling_simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base=3.3.3
  - mypy=0.790
  - notebook=6.1.5
  - numpy=1.19.4
  - pandas=1.1.4
  - pip=20.2.4
  - pytest=6.1.2
  - pytest-cov=2.10.1
  - python=3.8.6
  - scipy=1.5.3
  - seaborn=0.11.0
  - pip:
    - data-science-types==0.2.20
